### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by joeranbosma** [TIO-IKIM/TwixMRIAnonymizer#2]
Thank you for sharing this code! It works like a charm. I encountered two minor issues while following the documentation:
1. I had to change the filename to `anonymize.py` (https://github.com/TIO-IKIM/TwixMRIAnonymizer/blob/22df032176cfa21bfbeeae8185376365cef6df0a/README.md?plain=1#L38)
2. I had to add `create` to get `conda env create -n anonymizer python=3.11.2 -f requirements.txt` in https://github.com/TIO-IKIM/TwixMRIAnonymizer/blob/22df032176cfa21bfbeeae8185376365cef6df0a/README.md?plain=1#L29C8-L29C65

As for step 4, I think it could help users to indicate that the input and output should be folders (rather than directly linking to a specific .dat file).

All the best,
Joeran

**Comment by Remponator** [comment]
Hi Joeran,

thank you for pointing out these issues. I updated the repository accordingly. 

Regarding step 4, the tool should be able to accept files as input.

Best,
Moritz
